auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_tls_config:
    cert_file: /certs/cert.pem
    key_file: /certs/key.pem

common:
  path_prefix: /loki
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m                # fréquence optimisation & purge
  retention_enabled: true
  retention_delete_delay: 2h              # tampon avant suppression chunks
  retention_delete_worker_count: 100      # Concurrency pour suppression
  delete_request_store: filesystem        # Obligatoire si retention enabled :contentReference[oaicite:1]{index=1}

limits_config:
  retention_period: 720h                 # 30 jours retention globale

# Optionnel : régler concurrence de requêtes
# querier:
#   scheduler_worker_concurrency: 16
