global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: "local-observability"

scrape_configs:
  - job_name: "prometheus"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
    tls_config:
      insecure_skip_verify: true

  - job_name: "otel-collector"
    scheme: https
    static_configs:
      - targets: ["otel-collector:9888"]
    tls_config:
      insecure_skip_verify: true

  - job_name: "tempo"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["tempo:3200"]
    tls_config:
      insecure_skip_verify: true

  - job_name: "loki"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]
    tls_config:
      insecure_skip_verify: true

  - job_name: "grafana"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]
    tls_config:
      insecure_skip_verify: true

  - job_name: "localhost"
    metrics_path: /metrics
    scrape_timeout: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "proxmox"
    metrics_path: /pve
    params:
      target: ['192.168.1.254']
      cluster: ['1']
      node: ['1']
    static_configs:
      - targets: ["192.168.1.254:9221"]
