apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: https://prometheus:9090
    access: proxy
    jsonData: {tlsSkipVerify: true}
    isDefault: true

  - name: Loki
    type: loki
    url: https://loki:3100
    access: proxy
    jsonData: {tlsSkipVerify: true}

  - name: Tempo
    type: tempo
    url: https://tempo:3200
    access: proxy
    jsonData: {tlsSkipVerify: true}
